import type { CloudRegion, CloudProvider } from "./types";

export const PROVIDER_COLORS: Record<CloudProvider, string> = {
  aws: "#ff9900", azure: "#0078d4", gcp: "#34a853",
  cloudflare: "#f48120", oracle: "#f80000", alibaba: "#ff6a00", ibm: "#006699",
};
export const PROVIDER_NAMES: Record<CloudProvider, string> = {
  aws: "Amazon Web Services", azure: "Microsoft Azure", gcp: "Google Cloud Platform",
  cloudflare: "Cloudflare", oracle: "Oracle Cloud", alibaba: "Alibaba Cloud", ibm: "IBM Cloud",
};

export const CLOUD_REGIONS: CloudRegion[] = [
  // ── AWS ───────────────────────────────────────────────────────────────────
  {
    id:"aws-us-east-1", code:"us-east-1", name:"US East (N. Virginia)",
    provider:"aws", lat:38.13, lng:-78.45, city:"Ashburn", country:"United States",
    azCount:6, totalPowerMW:2400, usedPowerMW:1820,
    coolingType:"Air + Evaporative", tierLevel:"III", yearOpened:2006, floorSpaceSqM:185000,
    facilities:[
      { name:"Equinix DC-6",  operator:"Equinix",  powerMW:400, pue:1.20, tier:"III", certifications:["ISO 27001","SOC 2","PCI-DSS","FedRAMP"] },
      { name:"QTS Ashburn",   operator:"QTS",      powerMW:380, pue:1.22, tier:"III", certifications:["ISO 27001","SOC 2","HIPAA"] },
      { name:"CyrusOne IAD",  operator:"CyrusOne", powerMW:350, pue:1.18, tier:"III", certifications:["ISO 27001","SOC 2"] },
    ],
    services:["EC2","S3","RDS","Lambda","EKS","CloudFront","Route53","IAM"],
    connectedIXPs:["Equinix Ashburn (IAD)","DE-CIX New York"],
    upstreamProviders:["Cogent","Level3","NTT","Telia"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#ff9900", latencyMs:12,
    pricingTier:"standard", complianceFrameworks:["SOC2","ISO27001","PCI-DSS","FedRAMP","HIPAA"],
    sustainabilityScore:72, carbonFreeEnergy:65,
  },
  {
    id:"aws-us-west-2", code:"us-west-2", name:"US West (Oregon)",
    provider:"aws", lat:45.52, lng:-122.67, city:"Portland", country:"United States",
    azCount:4, totalPowerMW:1200, usedPowerMW:890,
    coolingType:"Evaporative", tierLevel:"III", yearOpened:2011, floorSpaceSqM:120000,
    facilities:[
      { name:"Hillsboro DC-1", operator:"Amazon",  powerMW:600, pue:1.15, tier:"III", certifications:["ISO 27001","SOC 2","FedRAMP"] },
      { name:"Hillsboro DC-2", operator:"Amazon",  powerMW:600, pue:1.14, tier:"III", certifications:["ISO 27001","SOC 2"] },
    ],
    services:["EC2","S3","RDS","Lambda","EKS","CloudFront"],
    connectedIXPs:["SIX Seattle","NWAX"],
    upstreamProviders:["Cogent","CenturyLink","GTT"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#ff9900", latencyMs:18,
    pricingTier:"standard", complianceFrameworks:["SOC2","ISO27001","FedRAMP"],
    sustainabilityScore:95, carbonFreeEnergy:100,
  },
  {
    id:"aws-eu-west-1", code:"eu-west-1", name:"Europe (Ireland)",
    provider:"aws", lat:53.33, lng:-6.25, city:"Dublin", country:"Ireland",
    azCount:3, totalPowerMW:720, usedPowerMW:540,
    coolingType:"Air", tierLevel:"III", yearOpened:2007, floorSpaceSqM:75000,
    facilities:[
      { name:"Clonshaugh DC",  operator:"Amazon",  powerMW:360, pue:1.25, tier:"III", certifications:["ISO 27001","SOC 2","GDPR"] },
      { name:"Tallaght DC",    operator:"Amazon",  powerMW:360, pue:1.23, tier:"III", certifications:["ISO 27001","SOC 2","GDPR"] },
    ],
    services:["EC2","S3","RDS","Lambda","EKS"],
    connectedIXPs:["INEX Dublin"],
    upstreamProviders:["Telia","GTT","PCCW"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#ff9900", latencyMs:22,
    pricingTier:"standard", complianceFrameworks:["GDPR","ISO27001","SOC2"],
    sustainabilityScore:88, carbonFreeEnergy:96,
  },
  {
    id:"aws-eu-central-1", code:"eu-central-1", name:"Europe (Frankfurt)",
    provider:"aws", lat:50.11, lng:8.68, city:"Frankfurt", country:"Germany",
    azCount:3, totalPowerMW:900, usedPowerMW:720,
    coolingType:"Air + Liquid", tierLevel:"III", yearOpened:2014, floorSpaceSqM:95000,
    facilities:[
      { name:"Equinix FR4",   operator:"Equinix",  powerMW:300, pue:1.28, tier:"III", certifications:["ISO 27001","SOC 2","GDPR","BSI C5"] },
      { name:"Interxion FRA", operator:"Interxion", powerMW:300, pue:1.30, tier:"III", certifications:["ISO 27001","SOC 2","GDPR"] },
      { name:"e-shelter FRA", operator:"e-shelter", powerMW:300, pue:1.22, tier:"III", certifications:["ISO 27001","GDPR","BSI C5"] },
    ],
    services:["EC2","S3","RDS","Lambda","EKS","CloudFront"],
    connectedIXPs:["DE-CIX Frankfurt"],
    upstreamProviders:["Deutsche Telekom","Telia","Cogent"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#ff9900", latencyMs:8,
    pricingTier:"premium", complianceFrameworks:["GDPR","ISO27001","SOC2","BSI C5"],
    sustainabilityScore:78, carbonFreeEnergy:71,
  },
  {
    id:"aws-ap-northeast-1", code:"ap-northeast-1", name:"Asia Pacific (Tokyo)",
    provider:"aws", lat:35.68, lng:139.69, city:"Tokyo", country:"Japan",
    azCount:4, totalPowerMW:1100, usedPowerMW:880,
    coolingType:"Air + Liquid", tierLevel:"III", yearOpened:2011, floorSpaceSqM:105000,
    facilities:[
      { name:"Equinix TY2",  operator:"Equinix",  powerMW:280, pue:1.35, tier:"III", certifications:["ISO 27001","SOC 2"] },
      { name:"NTT Com Tokyo", operator:"NTT",     powerMW:280, pue:1.30, tier:"III", certifications:["ISO 27001","SOC 2"] },
      { name:"Colt Tokyo",    operator:"Colt",    powerMW:280, pue:1.32, tier:"III", certifications:["ISO 27001"] },
    ],
    services:["EC2","S3","RDS","Lambda","EKS"],
    connectedIXPs:["JPIX Tokyo","JPNAP","Equinix Tokyo"],
    upstreamProviders:["NTT","KDDI","Softbank"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#ff9900", latencyMs:5,
    pricingTier:"premium", complianceFrameworks:["ISO27001","SOC2","FISC"],
    sustainabilityScore:60, carbonFreeEnergy:44,
  },
  {
    id:"aws-ap-south-1", code:"ap-south-1", name:"Asia Pacific (Mumbai)",
    provider:"aws", lat:19.07, lng:72.88, city:"Mumbai", country:"India",
    azCount:3, totalPowerMW:600, usedPowerMW:480,
    coolingType:"Air", tierLevel:"III", yearOpened:2016, floorSpaceSqM:55000,
    facilities:[
      { name:"CtrlS Mumbai",  operator:"CtrlS",   powerMW:200, pue:1.55, tier:"IV", certifications:["ISO 27001","SOC 2"] },
      { name:"Yotta Mumbai",  operator:"Yotta",   powerMW:200, pue:1.48, tier:"III", certifications:["ISO 27001"] },
      { name:"NxtGen Mumbai", operator:"NxtGen",  powerMW:200, pue:1.50, tier:"III", certifications:["ISO 27001","SOC 2"] },
    ],
    services:["EC2","S3","RDS","Lambda"],
    connectedIXPs:["DE-CIX Mumbai","Mumbai-IX"],
    upstreamProviders:["Tata","Reliance","BSNL"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#ff9900", latencyMs:15,
    pricingTier:"budget", complianceFrameworks:["ISO27001","SOC2","MeitY"],
    sustainabilityScore:38, carbonFreeEnergy:22,
  },

  // ── Azure ─────────────────────────────────────────────────────────────────
  {
    id:"az-eastus", code:"eastus", name:"East US",
    provider:"azure", lat:37.36, lng:-79.77, city:"Virginia", country:"United States",
    azCount:3, totalPowerMW:1800, usedPowerMW:1350,
    coolingType:"Air + Evaporative", tierLevel:"III", yearOpened:2008, floorSpaceSqM:165000,
    facilities:[
      { name:"Boydton DC-1",  operator:"Microsoft", powerMW:600, pue:1.18, tier:"III", certifications:["ISO 27001","SOC 2","FedRAMP","DoD IL4"] },
      { name:"Boydton DC-2",  operator:"Microsoft", powerMW:600, pue:1.17, tier:"III", certifications:["ISO 27001","SOC 2","FedRAMP"] },
      { name:"Boydton DC-3",  operator:"Microsoft", powerMW:600, pue:1.19, tier:"III", certifications:["ISO 27001","SOC 2"] },
    ],
    services:["VMs","Storage","SQL","AKS","Functions","Cognitive Services"],
    connectedIXPs:["Equinix Ashburn (IAD)"],
    upstreamProviders:["Level3","Cogent","Telia"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#0078d4", latencyMs:14,
    pricingTier:"standard", complianceFrameworks:["SOC2","ISO27001","FedRAMP","HIPAA","GDPR"],
    sustainabilityScore:100, carbonFreeEnergy:100,
  },
  {
    id:"az-westeurope", code:"westeurope", name:"West Europe",
    provider:"azure", lat:52.37, lng:4.89, city:"Amsterdam", country:"Netherlands",
    azCount:3, totalPowerMW:900, usedPowerMW:720,
    coolingType:"Air", tierLevel:"III", yearOpened:2010, floorSpaceSqM:88000,
    facilities:[
      { name:"AMS5",           operator:"Equinix",  powerMW:300, pue:1.24, tier:"III", certifications:["ISO 27001","SOC 2","GDPR"] },
      { name:"Interxion AMS",  operator:"Interxion",powerMW:300, pue:1.22, tier:"III", certifications:["ISO 27001","SOC 2","GDPR"] },
      { name:"Microsoft AMS",  operator:"Microsoft",powerMW:300, pue:1.20, tier:"III", certifications:["ISO 27001","GDPR"] },
    ],
    services:["VMs","Storage","SQL","AKS","Functions"],
    connectedIXPs:["AMS-IX Amsterdam","NL-ix"],
    upstreamProviders:["KPN","Telia","BT"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#0078d4", latencyMs:9,
    pricingTier:"standard", complianceFrameworks:["GDPR","ISO27001","SOC2"],
    sustainabilityScore:95, carbonFreeEnergy:100,
  },
  {
    id:"az-japaneast", code:"japaneast", name:"Japan East",
    provider:"azure", lat:35.68, lng:139.76, city:"Tokyo", country:"Japan",
    azCount:3, totalPowerMW:650, usedPowerMW:490,
    coolingType:"Air", tierLevel:"III", yearOpened:2014, floorSpaceSqM:62000,
    facilities:[
      { name:"Equinix TY4",   operator:"Equinix",  powerMW:220, pue:1.33, tier:"III", certifications:["ISO 27001","SOC 2"] },
      { name:"KDDI Toyosu",   operator:"KDDI",     powerMW:220, pue:1.30, tier:"III", certifications:["ISO 27001"] },
      { name:"AT Tokyo-1",    operator:"AT Tokyo", powerMW:210, pue:1.35, tier:"III", certifications:["ISO 27001","SOC 2"] },
    ],
    services:["VMs","Storage","SQL","AKS"],
    connectedIXPs:["JPIX Tokyo","Equinix Tokyo"],
    upstreamProviders:["NTT","KDDI","IIJ"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#0078d4", latencyMs:6,
    pricingTier:"premium", complianceFrameworks:["ISO27001","SOC2","FISC","My Number Act"],
    sustainabilityScore:62, carbonFreeEnergy:46,
  },

  // ── GCP ───────────────────────────────────────────────────────────────────
  {
    id:"gcp-us-central1", code:"us-central1", name:"us-central1 (Iowa)",
    provider:"gcp", lat:41.26, lng:-95.86, city:"Council Bluffs", country:"United States",
    azCount:4, totalPowerMW:1400, usedPowerMW:980,
    coolingType:"Evaporative", tierLevel:"III", yearOpened:2009, floorSpaceSqM:130000,
    facilities:[
      { name:"Council Bluffs DC-1", operator:"Google", powerMW:700, pue:1.12, tier:"III", certifications:["ISO 27001","SOC 2","FedRAMP"] },
      { name:"Council Bluffs DC-2", operator:"Google", powerMW:700, pue:1.11, tier:"III", certifications:["ISO 27001","SOC 2"] },
    ],
    services:["GCE","GCS","BigQuery","GKE","Cloud Run","Vertex AI"],
    connectedIXPs:["Any2 Chicago","Equinix Chicago"],
    upstreamProviders:["Level3","Telia","Cogent"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#34a853", latencyMs:20,
    pricingTier:"budget", complianceFrameworks:["SOC2","ISO27001","FedRAMP"],
    sustainabilityScore:100, carbonFreeEnergy:100,
  },
  {
    id:"gcp-europe-west1", code:"europe-west1", name:"europe-west1 (Belgium)",
    provider:"gcp", lat:50.44, lng:3.82, city:"St. Ghislain", country:"Belgium",
    azCount:3, totalPowerMW:750, usedPowerMW:540,
    coolingType:"Evaporative", tierLevel:"III", yearOpened:2012, floorSpaceSqM:72000,
    facilities:[
      { name:"St. Ghislain DC", operator:"Google", powerMW:750, pue:1.09, tier:"III", certifications:["ISO 27001","SOC 2","GDPR"] },
    ],
    services:["GCE","GCS","BigQuery","GKE","Cloud Run"],
    connectedIXPs:["AMS-IX","BNIX"],
    upstreamProviders:["Telia","BT","Level3"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#34a853", latencyMs:11,
    pricingTier:"standard", complianceFrameworks:["GDPR","ISO27001","SOC2"],
    sustainabilityScore:100, carbonFreeEnergy:100,
  },
  {
    id:"gcp-asia-northeast1", code:"asia-northeast1", name:"asia-northeast1 (Tokyo)",
    provider:"gcp", lat:35.66, lng:139.74, city:"Tokyo", country:"Japan",
    azCount:3, totalPowerMW:580, usedPowerMW:420,
    coolingType:"Air", tierLevel:"III", yearOpened:2016, floorSpaceSqM:54000,
    facilities:[
      { name:"Equinix TY3",  operator:"Equinix",  powerMW:200, pue:1.34, tier:"III", certifications:["ISO 27001","SOC 2"] },
      { name:"Telehouse TKY", operator:"Telehouse", powerMW:190, pue:1.31, tier:"III", certifications:["ISO 27001"] },
      { name:"ITOCHU IaaS",   operator:"ITOCHU",   powerMW:190, pue:1.36, tier:"III", certifications:["ISO 27001","SOC 2"] },
    ],
    services:["GCE","GCS","BigQuery","GKE","Cloud Run"],
    connectedIXPs:["JPIX Tokyo","JPNAP"],
    upstreamProviders:["NTT","Softbank","KDDI"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"region", color:"#34a853", latencyMs:7,
    pricingTier:"premium", complianceFrameworks:["ISO27001","SOC2","FISC"],
    sustainabilityScore:100, carbonFreeEnergy:100,
  },

  // ── Cloudflare PoPs ───────────────────────────────────────────────────────
  { id:"cf-ord", code:"ORD", name:"Cloudflare Chicago",
    provider:"cloudflare", lat:41.97, lng:-87.91, city:"Chicago", country:"United States",
    azCount:1, totalPowerMW:18, usedPowerMW:12, coolingType:"Air", tierLevel:"III",
    yearOpened:2015, floorSpaceSqM:800,
    facilities:[{ name:"Equinix CH1", operator:"Equinix", powerMW:18, pue:1.28, tier:"III", certifications:["SOC 2"] }],
    services:["CDN","Workers","R2","DDoS","Magic Transit"],
    connectedIXPs:["Any2 Chicago","Equinix Chicago"],
    upstreamProviders:["Cogent","Level3","GTT"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"pop", color:"#f48120", latencyMs:8,
    pricingTier:"budget", complianceFrameworks:["SOC2"],
    sustainabilityScore:100, carbonFreeEnergy:100,
  },
  { id:"cf-lhr", code:"LHR", name:"Cloudflare London",
    provider:"cloudflare", lat:51.47, lng:-0.46, city:"London", country:"United Kingdom",
    azCount:1, totalPowerMW:22, usedPowerMW:15, coolingType:"Air", tierLevel:"III",
    yearOpened:2014, floorSpaceSqM:950,
    facilities:[{ name:"Equinix LD4", operator:"Equinix", powerMW:22, pue:1.25, tier:"III", certifications:["SOC 2","ISO 27001"] }],
    services:["CDN","Workers","R2","DDoS","Magic Transit"],
    connectedIXPs:["LINX London","LONAP"],
    upstreamProviders:["Cogent","BT","Level3"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"pop", color:"#f48120", latencyMs:5,
    pricingTier:"budget", complianceFrameworks:["SOC2","ISO27001","GDPR"],
    sustainabilityScore:100, carbonFreeEnergy:100,
  },
  { id:"cf-fra", code:"FRA", name:"Cloudflare Frankfurt",
    provider:"cloudflare", lat:50.03, lng:8.57, city:"Frankfurt", country:"Germany",
    azCount:1, totalPowerMW:25, usedPowerMW:18, coolingType:"Air", tierLevel:"III",
    yearOpened:2013, floorSpaceSqM:1100,
    facilities:[{ name:"Equinix FR5", operator:"Equinix", powerMW:25, pue:1.22, tier:"III", certifications:["SOC 2","ISO 27001","GDPR"] }],
    services:["CDN","Workers","R2","DDoS","Magic Transit"],
    connectedIXPs:["DE-CIX Frankfurt"],
    upstreamProviders:["Telia","Cogent","GTT"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"pop", color:"#f48120", latencyMs:4,
    pricingTier:"budget", complianceFrameworks:["SOC2","ISO27001","GDPR","BSI C5"],
    sustainabilityScore:100, carbonFreeEnergy:100,
  },
  { id:"cf-sin", code:"SIN", name:"Cloudflare Singapore",
    provider:"cloudflare", lat:1.35, lng:103.99, city:"Singapore", country:"Singapore",
    azCount:1, totalPowerMW:20, usedPowerMW:14, coolingType:"Air", tierLevel:"III",
    yearOpened:2014, floorSpaceSqM:900,
    facilities:[{ name:"Equinix SG1", operator:"Equinix", powerMW:20, pue:1.40, tier:"III", certifications:["SOC 2","ISO 27001"] }],
    services:["CDN","Workers","R2","DDoS"],
    connectedIXPs:["BBIX Singapore","Equinix Singapore"],
    upstreamProviders:["Singtel","StarHub","M1"],
    ipv6:true, status:"operational", statusMessage:"All systems operational",
    tier:"pop", color:"#f48120", latencyMs:6,
    pricingTier:"budget", complianceFrameworks:["SOC2","MTCS"],
    sustainabilityScore:82, carbonFreeEnergy:74,
  },
];
