import type { IXP } from "./types";

export const IXP_DATA: IXP[] = [
  { id:1,  name:"DE-CIX Frankfurt", shortName:"DE-CIX",  city:"Frankfurt",    country:"Germany",      lat:50.11,  lng:8.68,    trafficGbps:14200, memberCount:1000, networks:["Deutsche Telekom","Cogent","Lumen","Telia"],    peeringPolicy:"open",       status:"active", website:"https://de-cix.net" },
  { id:2,  name:"AMS-IX",           shortName:"AMS-IX",  city:"Amsterdam",    country:"Netherlands",  lat:52.37,  lng:4.90,    trafficGbps:11000, memberCount:950,  networks:["NTT","GTT","Zayo","Cogent","KPN"],               peeringPolicy:"open",       status:"active", website:"https://ams-ix.net" },
  { id:3,  name:"LINX",             shortName:"LINX",    city:"London",       country:"UK",           lat:51.51,  lng:-0.13,   trafficGbps:7800,  memberCount:880,  networks:["BT","Virgin","Sky","TalkTalk","Vodafone"],       peeringPolicy:"open",       status:"active", website:"https://linx.net" },
  { id:4,  name:"NYIIX",            shortName:"NYIIX",   city:"New York",     country:"USA",          lat:40.71,  lng:-74.01,  trafficGbps:4200,  memberCount:310,  networks:["Verizon","Comcast","AT&T","Sprint"],             peeringPolicy:"selective",  status:"active", website:"https://nyiix.net" },
  { id:5,  name:"SIX",              shortName:"SIX",     city:"Seattle",      country:"USA",          lat:47.61,  lng:-122.33, trafficGbps:1800,  memberCount:270,  networks:["Comcast","CenturyLink","Zayo"],                  peeringPolicy:"open",       status:"active", website:"https://seattleix.net" },
  { id:6,  name:"Equinix San Jose", shortName:"SJC-IX",  city:"San Jose",     country:"USA",          lat:37.34,  lng:-121.89, trafficGbps:3500,  memberCount:420,  networks:["Comcast","AT&T","NTT","Level3"],                 peeringPolicy:"selective",  status:"active", website:"https://equinix.com" },
  { id:7,  name:"JPIX",             shortName:"JPIX",    city:"Tokyo",        country:"Japan",        lat:35.68,  lng:139.65,  trafficGbps:6200,  memberCount:220,  networks:["NTT","KDDI","SoftBank","IIJ"],                   peeringPolicy:"selective",  status:"active", website:"https://jpix.ad.jp" },
  { id:8,  name:"SGIX",             shortName:"SGIX",    city:"Singapore",    country:"Singapore",    lat:1.35,   lng:103.82,  trafficGbps:2800,  memberCount:320,  networks:["SingTel","StarHub","M1","Starhub"],              peeringPolicy:"open",       status:"active", website:"https://sgix.sg" },
  { id:9,  name:"Equinix Paris",    shortName:"PAR-IX",  city:"Paris",        country:"France",       lat:48.86,  lng:2.35,    trafficGbps:4100,  memberCount:380,  networks:["Orange","Free","Bouygues","SFR"],                peeringPolicy:"open",       status:"active", website:"https://equinix.com" },
  { id:10, name:"MSK-IX",           shortName:"MSK-IX",  city:"Moscow",       country:"Russia",       lat:55.76,  lng:37.62,   trafficGbps:5900,  memberCount:590,  networks:["Rostelecom","MTS","Beeline","MegaFon"],          peeringPolicy:"selective",  status:"active", website:"https://msk-ix.ru" },
  { id:11, name:"HKIX",             shortName:"HKIX",    city:"Hong Kong",    country:"Hong Kong",    lat:22.32,  lng:114.17,  trafficGbps:3200,  memberCount:280,  networks:["PCCW","HGC","i-cable","Hutchison"],              peeringPolicy:"open",       status:"active", website:"https://hkix.net" },
  { id:12, name:"TORIX",            shortName:"TORIX",   city:"Toronto",      country:"Canada",       lat:43.65,  lng:-79.38,  trafficGbps:1200,  memberCount:195,  networks:["Bell","Rogers","Telus","Shaw"],                  peeringPolicy:"open",       status:"active", website:"https://torix.ca" },
  { id:13, name:"NAP Africa JB",    shortName:"NAPJB",   city:"Johannesburg", country:"South Africa", lat:-26.20, lng:28.05,   trafficGbps:890,   memberCount:140,  networks:["Telkom","MTN","Vodacom","Cell C"],               peeringPolicy:"open",       status:"active", website:"https://napafrica.net" },
  { id:14, name:"IX.br São Paulo",  shortName:"IX.br",   city:"São Paulo",    country:"Brazil",       lat:-23.55, lng:-46.63,  trafficGbps:8400,  memberCount:2800, networks:["Claro","Vivo","TIM","NET"],                      peeringPolicy:"open",       status:"active", website:"https://ix.br" },
  { id:15, name:"KINX",             shortName:"KINX",    city:"Seoul",        country:"South Korea",  lat:37.57,  lng:126.98,  trafficGbps:2100,  memberCount:185,  networks:["SK Telecom","KT","LG U+","Sejong"],              peeringPolicy:"selective",  status:"active", website:"https://kinx.net" },
  { id:16, name:"DE-CIX Mumbai",    shortName:"DE-CIX",  city:"Mumbai",       country:"India",        lat:19.08,  lng:72.88,   trafficGbps:1800,  memberCount:230,  networks:["Tata","Airtel","BSNL","Reliance"],               peeringPolicy:"open",       status:"active", website:"https://de-cix.net/in/mumbai" },
  { id:17, name:"SwissIX",          shortName:"SwissIX", city:"Zurich",       country:"Switzerland",  lat:47.38,  lng:8.54,    trafficGbps:980,   memberCount:160,  networks:["Swisscom","Sunrise","Init7","Colt"],             peeringPolicy:"open",       status:"active", website:"https://swissix.ch" },
  { id:18, name:"ESPANIX",          shortName:"ESPANIX", city:"Madrid",       country:"Spain",        lat:40.42,  lng:-3.70,   trafficGbps:1200,  memberCount:145,  networks:["Telefonica","Vodafone ES","Orange ES","MásMóvil"],peeringPolicy:"open",       status:"active", website:"https://espanix.net" },
  { id:19, name:"MIX-IT",           shortName:"MIX-IT",  city:"Milan",        country:"Italy",        lat:45.47,  lng:9.19,    trafficGbps:1400,  memberCount:175,  networks:["Telecom Italia","Vodafone IT","Wind","Fastweb"],  peeringPolicy:"open",       status:"active", website:"https://mix-it.net" },
  { id:20, name:"DE-CIX Dubai",     shortName:"DE-CIX",  city:"Dubai",        country:"UAE",          lat:25.20,  lng:55.27,   trafficGbps:800,   memberCount:110,  networks:["Etisalat","du","Ooredoo"],                       peeringPolicy:"selective",  status:"active", website:"https://de-cix.net/ae/dubai" },
];
